### ISSUE TITLE
TODO: An issue to track everything that I decided to procrastinate

### ISSUE THREAD

**Issue by Varad-13** [Tags-Based-Recommendation-Engine/scripts#1]
- [ ] - Add manual control to each script
- [x] - Add configs for automigration/interactive migration/no migration
- [ ] - Add function to update databases under /data/
- [ ] - Add function to let user import database from /data automatically. Test if this works fine with django migration.
- [ ] - Move branch version from config.xml to .github/repositories.json
